describe('User Login Flow', () => {

  beforeEach(() => {
    cy.intercept('POST', '**/auth/login').as('loginApi')
    cy.visit('/login')
  })

  it('should show error message for invalid credentials', () => {
    cy.login('invalid@example.com', 'wrongpassword')

    cy.wait('@loginApi')
      .its('response.statusCode')
      .should('be.oneOf', [400, 401])

    cy.contains(/invalid|failed|not found/i).should('be.visible')
  })


  it('should login successfully and redirect to student dashboard', () => {
    // Reading the credentials generated by the registration test
    cy.fixture('testUser.json').then((user) => {
      cy.login(user.email, user.password)

      cy.wait('@loginApi').its('response.statusCode').should('eq', 200)

      cy.url().should('include', '/student/dashboard')

      cy.contains(/Dashboard/i).should('be.visible')
    })
  })

})